### PR TITLE
Update SPEC.md

### PR DESCRIPTION
**Pull request by jgkomand**

### CODE REVIEW

**Comment by jgkomand** [comment]
This change needs to regenerate the table of contents. @jonschipp had some thoughts on the markdown:

The markdown has great info and is very detailed. Since it's written in the format of Step 1, Step 2, etc, it feels like a tutorial. You had mentioned breaking out everything from Step 3 and beyond into a separate markdown - what do you think about breaking it out into 2 markdowns, one which has a step by step tutorial on creating a plugin, and one which documents the structure of a plugin spec and the different actions you can take on the command line when working with your plugin (i.e. code generation, plugin commands, registering, etc). The tutorial would reference these actions, and the two files would be intended to be used side by side. The goal here would be to provide clarity, by separating the explanation of the sdk with instructions on how to make a plugin. Let me know what you think!

**Comment by jonschipp** [comment]
I think that's a good idea

**Comment by jonschipp** [comment]
I would mention that `make` calls `make runner` which creates the `*-run` script

**Comment by jgkomand** [comment]
Ok will do. What do you think about adding some go examples here for implementing an action as well?

**Comment by jonschipp** [comment]
Sounds good to me

**Pull request merged**
